ALTER TABLE  clientes ADD fecha_date DATE;

UPDATE clientes
SET fecha_date = STR_TO_DATE(FECHA_APERTURA_TARJETA, '%Y-%m-%d');

ALTER TABLE clientes DROP COLUMN FECHA_APERTURA_TARJETA;

ALTER TABLE clientes CHANGE COLUMN fecha_date FECHA_APERTURA_TARJETA DATE;

ALTER TABLE  transacciones ADD fecha_date DATE;

UPDATE transacciones
SET fecha_date = STR_TO_DATE(FECHA_TRANSACCION, '%Y-%m-%d')
WHERE FECHA_TRANSACCION <> '';

ALTER TABLE transacciones DROP COLUMN FECHA_TRANSACCION;

ALTER TABLE transacciones CHANGE COLUMN fecha_date FECHA_TRANSACCION DATE;