SELECT min(FECHA_TRANSACCION) INTO @Fecha_desde
FROM transacciones;

SELECT max(FECHA_TRANSACCION) INTO @Fecha_hasta
FROM transacciones;

SET @n = 2;

SELECT
	t1.IDENTIFICACIÓN, 
	t1.CODIGO_CATEGORIA, 
	t1.TRX, 
	max(t2.FECHA_TRANSACCION) as fecha
FROM (
	SELECT DISTINCT
		t2.IDENTIFICACIÓN, 
		t3.CODIGO_CATEGORIA, 
		COUNT(DISTINCT(t1.ID_TRANSACCION)) AS TRX,
		ROW_NUMBER() OVER (PARTITION BY t2.IDENTIFICACIÓN ORDER BY COUNT(DISTINCT(t1.ID_TRANSACCION)) DESC) AS row_num
	FROM transacciones t1
		INNER JOIN clientes t2 ON (t1.IDENTIFICACION = t2.IDENTIFICACIÓN)
		INNER JOIN categorias_consumo t3 ON (t1.CODIGO_CATEGORIA = t3.CODIGO_CATEGORIA)
	WHERE (t1.FECHA_TRANSACCION between @Fecha_desde and @Fecha_hasta)
	GROUP BY t2.IDENTIFICACIÓN, T3.CODIGO_CATEGORIA
	ORDER BY t2.IDENTIFICACIÓN, TRX DESC
) t1 
	INNER JOIN transacciones t2 ON (t1.IDENTIFICACIÓN = t2.IDENTIFICACION 
												AND t1.CODIGO_CATEGORIA = t2.CODIGO_CATEGORIA)
WHERE t1.row_num <= @n
GROUP BY t1.IDENTIFICACIÓN, t1.CODIGO_CATEGORIA, t1.TRX
ORDER BY t1.IDENTIFICACIÓN, fecha DESC;
